# Generated by Django 4.1.2 on 2022-10-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('language_target', models.CharField(max_length=32)),
                ('extension', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=8)),
                ('repo_uri', models.CharField(max_length=256)),
                ('version', models.CharField(max_length=8)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('result', models.CharField(max_length=16)),
                ('issue_text', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('use_stdin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=8)),
                ('semester', models.CharField(max_length=8)),
                ('deadline', models.DateField()),
            ],
            options={
                'unique_together': {('version', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('semester', models.CharField(max_length=8)),
                ('repo_uri', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=32)),
                ('compile', models.BooleanField()),
                ('run', models.CharField(max_length=1024)),
            ],
            options={
                'unique_together': {('semester', 'repo_uri')},
            },
        ),
    ]
